### ISSUE TITLE
替换掉res50后输出大小不匹配

### ISSUE THREAD

**Issue by whut2962575697** [hudingding/TridentNet-mmdetection#2]
你好，我在使用过程中遇到了一点问题，替换掉res50后输出维度与Gt不匹配
![image](https://user-images.githubusercontent.com/25346526/77870041-f4602000-7272-11ea-89e8-833daa6b6570.png)

**Comment by Ryanibb** [comment]
> 你好，我在使用过程中遇到了一点问题，替换掉res50后输出维度与Gt不匹配
> ![image](https://user-images.githubusercontent.com/25346526/77870041-f4602000-7272-11ea-89e8-833daa6b6570.png)

请问这个问题怎么解决的呢
